name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: Checkout repo
      #  uses: actions/checkout@v2
  
      - uses: actions/checkout@master
        with:
          ref: feature/github-actions        
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: Install Dependencies
        run: yarn install
      - name: Build Popcorn-TV App
        run: yarn build
      #- name: Install deps
      #  run: npm install

      #- name: Install packages
      #  run: npm run install-packages


      # - name: Lint
      #   run: npm run lint

      #- name: Build
      #  run: npm run build
      # Linux
      #- name: Build for Linux
      #  run: electron-packager . PopcornTV --platform=linux --arch=x64 --version=0.30.0 --icon Resources/Mac/icon.icns --ignore "/Mac.zip|Windows.zip|Linux.zip/g" --overwrite
